### ISSUE TITLE
Utarbeide overordnet grid

### ISSUE THREAD

**Issue by Lillebo** [navikt/Designsystemet-old#111]
- [ ] Vurdere dagens grid, evt. erstatte (basert på gammel Bootstrap)
- [x] Grid settes opp i sketch
- [x] Utarbeide retningslinjer for grid
- [x] Vurdere regler for responsivitet
- [x] Vurdere regler for avstander (spacing)
- [x] Vurdere sidebredder, føringer for layout generelt
- [ ] Vurdere grid som er tilpasset eksterne og interne flater (forskjellen mellom de er justering på "gutter" bredde, ekstern har bredere, intern har smalere)
- [ ] Vurdere spacing størrelser (se kommentar lenger nede)

**Comment by Miaag** [comment]
Ifb med grid og spacing. Syns vi skal se nærmere på hvordan vi kan skape et system av "visual spacing", med såkalte tskjorte størrelser (s,m,l,xl). De er lettere å huske og forholde seg til. 

Snakker da om grid og spacing som sammen blir et "spatial system". Grid er et komponent som bruker space. Visuell spacing er space begreper (s,m,lxl) innenfor hele komponent biblioteket. Se bilde.

<img width="658" alt="Skjermbilde 2019-11-22 kl  14 05 36" src="https://user-images.githubusercontent.com/54023370/69428968-c9007e00-0d32-11ea-83ce-8a7ca96356c5.png">

**Comment by unorsk** [comment]
1. Jeg er litt usikker om det er noen fordeler ved bruk av 2px minst størrelsen. Fordi den er altfor granular. Det gir så my fleksibilitet at det er nesten det samme som å si at 1px er minst størrelsen (som egentlig betyr at vi ikke har noen grid i det hele tatt)

2. Også er det viktig at vi ikke glemmer om typografi. Og revurderer font-størrelser og baselines som vi bruker nå. Fordi noen av dem som er bruk nå skal ikke passe inn i det nye 4px(8px) baseline grid. Men det også kan bety at mange komponentene våre må også justeres litt.

3. Størrelser som f.eks **X** eller **XL** betyr veldig lite utenfor kontekst. Det er godt å ha definisjoner som f.eks: en header av xxl størrelse må ha xxl spacing under den.

4. Vertical spacing 4px gjør mening bare i typografi og ikoner. Bortsett fra det, skal 4px ikke brukes. Minst vertical avstand kan være 8px.

**Comment by unorsk** [comment]
<img width="527" alt="Screenshot 2020-01-21 at 08 38 26" src="https://user-images.githubusercontent.com/25188/72784742-c4b8ea00-3c29-11ea-93b5-983e8f2f369e.png">

<img width="528" alt="Screenshot 2020-01-21 at 08 38 33" src="https://user-images.githubusercontent.com/25188/72784759-cb476180-3c29-11ea-9af9-2cb92dba979a.png">

<img width="255" alt="Screenshot 2020-01-21 at 08 38 45" src="https://user-images.githubusercontent.com/25188/72784764-cf737f00-3c29-11ea-8ccd-b45fa0b74334.png">

<img width="359" alt="Screenshot 2020-01-21 at 08 38 53" src="https://user-images.githubusercontent.com/25188/72784771-d3070600-3c29-11ea-9e31-dc814259be2d.png">

<img width="483" alt="Screenshot 2020-01-21 at 08 39 05" src="https://user-images.githubusercontent.com/25188/72784775-d7cbba00-3c29-11ea-852f-390e9a084641.png">

<img width="782" alt="Screenshot 2020-01-21 at 08 39 17" src="https://user-images.githubusercontent.com/25188/72784779-dbf7d780-3c29-11ea-84ab-a3df5e058f00.png">

<img width="622" alt="Screenshot 2020-01-21 at 08 39 33" src="https://user-images.githubusercontent.com/25188/72784790-e1edb880-3c29-11ea-9b82-b9935cd318e8.png">

**Comment by unorsk** [comment]
Etter en samtale med @Lillebo har vi kommet til en alternativ løsning:

1. 8x8 px avstandsystem mellom elementer
2. 4x4 px avstandsystem for padding inni i elementer
3. Vi bruker brekkpunkter for å endre marginer (16px på mobil, 24px på tablet og større)
4. 960px er maks størrelse som kan brukes på eksterne flater
5. Vi utvikler et par `common used (and recommended) templates`

**Comment by Lillebo** [comment]
Ting vi snakket om i sprintplanleggingen i dag:

- Wei har laget en egen variant av Material Design grid hvor eneste forskjell var maks sidebredde?
    - Vurdere om vi kan droppe å ha egne føringer for sidebredde slik at vi kan si at vi adopterer Material sitt grid uendret?
- Lansering/publisering av nytt grid bør gjøres samtidig som vi skriver litt om det til brukerne våre
    - F.eks. om det nye gridet bør appliseres på gamle sidermaler/sidetyper, eller om dette kun er tenkt for redesign-prosjektet i regi av Team Personbruker og evt. interne flater?
