### ISSUE TITLE
Engelske navn på komponenter

### ISSUE THREAD

**Issue by Lillebo** [navikt/Designsystemet-old#113]
- [x] Beslutte norsk eller engelsk navngiving
- [x] Omdøpe alt til engelsk i Sketch
- [ ] Skrive om alt til engelsk i frontend (relatert frontend-task: https://github.com/navikt/nav-frontend-moduler/issues/588)
- [ ] Gjennomgang navn på komponenter samsvar mellom design og kode (figma/sketch)

**Comment by unorsk** [comment]
- [x] Engelsk.

Det er ikke mye å tenke om, egentlig. Siden vi har allerede snakket om det mange ganger og jeg tror at flest er enige om at komponenter og stiler osv må ha engelske navn. Det samme gjelder Sketch-biblioteket. 

Men hvis vi fortsatt har tvil om det, da kan vi publisere denne beslutningen og gi to uker (eller til Januar f.eks) slik at alle som ikke er enig med det, kan uttale sine argumenter. Hvis vi ikke får noen argumenter imot, da setter vi jobben i gang og omskriver alt til engelsk.

**Comment by Lillebo** [comment]
Er nok litt enig der @unorsk. Ser heller ingen umiddelbart gode grunner til å ha disse tingene på norsk.

**Comment by Miaag** [comment]
Designsystemet har besluttet at alle komponenter skal omdøpes til engelske navn.

**Comment by KenAJoh** [comment]
https://github.com/navikt/nav-frontend-moduler/tree/master/%40navikt/ds-react
