### ISSUE TITLE
Mønster/retningslinjer for å formidle skjemakrav til bruker

### ISSUE THREAD

**Issue by Lillebo** [navikt/Designsystemet-old#135]
Vi trenger retningsnlinjer og muligens et eget mønster for hvordan vi best kan kommunisere kravene for riktig utfylling av skjema til bruker - uten at bruker skal være nødt til å få noen feilmeldinger fra validering først.

Avklare hvordan vi løser:

- [ ] påkrevd vs. valgfri (se #3)
- [ ] spesielle input-formater (datoer, tlf, fnr, space vs. `type="number"` osv. [[ref. retningslinjer for tall-formater her](https://design.nav.no/resources/language/units)])
- [ ] andre krav/instruksjoner som må forklares mer inngående (bruk av [Hjelpetekst](https://design.nav.no/components/hjelpetekst#kombinasjon-med-skjemafelt) osv)
- [ ] unntak for avanserte skjema (ekspertsystemer)?

Lage/publisere:

- [ ] Retningslinjer
- [ ] Mønster
