### ISSUE TITLE
Rydde i Abstract

### ISSUE THREAD

**Issue by Lillebo** [navikt/Designsystemet-old#150]
### Problem

Nå har vi mye eksperimentell/work-in-progress design på **master** i Abstract:

<img width="965" alt="Screenshot 2020-02-05 at 08 45 40" src="https://user-images.githubusercontent.com/74510/73822589-b86e8880-47f6-11ea-989f-e60983097568.png">

Med Git skal master alltid være **source of truth** og bør da kun inneholde ting som er *ferdig, vedtatt og gjeldende*.

Eksperimenter og ting som er under arbeid skal alltid ligge i en egen sub-branch.

Vi begynner også å få veldig mange sub brancher i prosjektet:

<img width="246" alt="Screenshot 2020-02-05 at 09 08 47" src="https://user-images.githubusercontent.com/74510/73823170-05069380-47f8-11ea-91f1-a2f8d926ea43.png">

Mange av disse virker å være gamle og inaktive, flere av dem er opprettet av folk utenfor Designsystem-teamet, og det virker ikke å være noen regler for navngiving eller struktur på dem.

### Løsning

Jeg foreslår at vi tar en skikkelig ryddesjau i Abstract og gjør følgende:

- [ ] Fjerner all eksperimentell design fra master og legger dem i egne sub-brancher
- [ ] Fjerne alle gamle, inaktive branches
- [ ] Fjerner alle branches som er opprettet av folk utenfor Designsystem-teamet (gi dem beskjed først slik at de kan ta backup hvis de vil)
- [ ] Etablere en regel hvor kun medlemmer av Designsystem-teamet får lov til å opprette branches på prosjektet fra nå av
- [ ] Etablere en regel for navngiving av branches (se: https://uxplanet.org/mastering-the-abstract-workflow-b204e28e335c)
- [ ] Etablere en regel om at vi alltid tar review av ting som skal merges inn i master
