### ISSUE TITLE
Lenke liste

### ISSUE THREAD

**Issue by sergiohaisch** [navikt/Designsystemet-old#62]
Samle informasjon om
- [ ] Bruk av lenke lister
- [ ] Behov for ulike typer lenke lister (navigasjonsmenyer, redaksjonelle lister, strukturelle lister osv.) -> Hvor mange trenger vi?
- [ ] Høre med Karina hvilke føringer som foreligger fra et tilgjengelighetsperspektiv

Relatert til #95
Relatert til #47

**Comment by karinaldw** [comment]
Noen eksempler fra andre sider:

![nrk](https://user-images.githubusercontent.com/30718528/66304438-72afbb00-e8fd-11e9-9930-db7bd7559e2f.png)
![regjeringen](https://user-images.githubusercontent.com/30718528/66304445-76434200-e8fd-11e9-953c-b95f4d13e130.png)
![helsenorge](https://user-images.githubusercontent.com/30718528/66304451-7b07f600-e8fd-11e9-8c34-92984ca2f82d.png)

**Comment by karinaldw** [comment]
Man MÅ ikke ha understreking som på de andre lenkene, men trenger da en annen tydelig markering (utover farge) for å vise at dette er lenker. Bra hvis lenkelistene har nok spacing og kanskje (venstrestilt) chevron. Kan hjelpe oss å gå mer i den retningen å ha chevrons på venstre side (istedenfor på høyre side og ofte alt for langt vekk fra selve lenketeksten).

**Comment by finiteattention** [comment]
Heftig +1 fra meg om venstrestilte piler (overalt, ikke bare ved lenketekst). Noen grunner:

- Ryddigere (både visuelt og idet du klikker på samme sted uansett hvor lang lenketeksten er)
- Lettere sett i sammenhengen med selve tekst/element (f. eks. ved bruk av forstørrelsesverktøy)
- Mindre bry for folk som tror at de må klikke på selve pilen for å komme seg videre (som mange har blitt opplært til å gjøre ved å ha faktisk brukt internettet 🙄 ). Dette straffer alle sånne brukere, men kanskje først og fremst de med dårlig finmotorikk. 

Stiller (noen måtte) med forslag fra GOV.UK verden. Første eksempel brukes i "Related content"-sidespalta. Jeg liker at den er ryddig, med tilstrekkelig plass og luft rundt enkelte lenker. Savner ikke nødvendigvis piler.

Andre eksempel brukes under hovedartikkelen. Her er det halvfet tekst på lenkene. Jeg mener at dette er litt vanskeligere å lese, både pga at halfvet generelt sett kan være vanskelig å lese, men jeg får også følelsen om at tykkere tekst har ført til mindre luft mellom lenker, selv om listene skal være likt mtp mellomrom.

Tredje kommer fra GOV.UK-footeren. Her er det mye plass, som jeg elsker. Kan hende dette er samme spacing som med eksempel 1 ovenfor, men av en eller annen grunn oppfatter jeg dette som luftigere. Noen som er hypp på grafisk design får gjerne si meg hva det er!

I alle tre tilfeller er lenkene understreket. Her er jeg litt delt: understrek gjør det vanskeligere å lese (og her er understreking gjort på den vanlige måten, som gjør at den egentlig er ganske tett på teksten :/ ), men det er så innmari fint å vite, sånn umiddelbart, at noe er lenketekst.

![image](https://user-images.githubusercontent.com/6875491/66307190-12704780-e904-11e9-836f-c00a9e21460b.png)

![image](https://user-images.githubusercontent.com/6875491/66307608-2bc5c380-e905-11e9-8150-557d34a092ae.png)

![image](https://user-images.githubusercontent.com/6875491/66307574-0f298b80-e905-11e9-9639-4bc5cbf2f52c.png)
